language: python
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - black --diff --check airpixel/ setup.py
  - pylint airpixel/ setup.py
  - pytest
