dist: xenial
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  python: '3.7'
  provider: pypi
  user: mmEissen
  password:
    secure: MNgdP9RhxaWTnZgJ3NEtvRyfqT/jS/CkbIIqN51dYP+yAtRWsrJBFSuvZwelKilOSzPITxnhUOZZnKa6omzc4Gm9oGWmBmSESC2fTQpa9OjBVLWx1obh2O4E0FhPR4YvlXKfR7STOY4kxOXI9oidXZAXVbaO7e+2/7EssFQed6XvPT4d2nCNM3szAzjBTqnbPbvjYtDAjd/V5UCU0VpK9pTJsy52ZSthfzv+SlgEEm/pAY89YgV6vGrBHqJAA5HCySzeXEI2QXeQ9jrJTa7cZjLmFZDjWSS5Lz7NZBQKWwSX2ezueF0q7OI6s0BzxWqFr1ffFEfi1reNRfcvG3KgJA/QjFqm6KD6K6ZQeEPx5oZqWNl34ZNpW5NlsSWLJNa1NQJ7GZPzvHerO6rxdIOgKRsUbMvgpCpKMiuyUUOYVqe/tUe2LzhAsPCq7XJaqav2E86LtjR+WanvkpI2FHP2hg1nya9SzbRxm/Y6wcBa/5okyB5SUCt94JgCw0uqEAO51kPFTj/g4QRxG3hGRimmcuoSQvcKNEn4hnSL2E3pliLS10J+LBfnBKPCnKJVmuWFBwpTFQDXNzHsOdj9lqDz5y/0uwuyeVbmtfPXDoF+ZWqHPVXuR/DbeIcwTJbBjXkAlKPnTMhNNDnDBMeRuZ/9BSqbgDbOKfOy4m61dCWtL6Q=
  on:
    branch: master
