name: Docker Release

on:
  pull_request:
    branches: 
      - master
      - dev
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: mmeissen
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - 
        name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./ArduinoNanoIOT
          file: ./ArduinoNanoIOT/Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: user/app:latest

