name: Package Release

on:
  pull_request:
    branches: 
      - master
      - dev
  push:
    branches:
      - master

jobs:
  quality_assurance:
    runs-on: ubuntu-latest
    container:
      image:  python:3.8-buster
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: poetry install
      - name: Check Version
        run: |
          package_name=$(poetry version --no-ansi | grep --color=never -Po "^\S*")
          this_version=$(poetry version --no-ansi | grep --color=never -Po "([0-9]|\.)+")
          remote_version=$(poetry search $package_name --no-ansi | grep --color=never -Po "([0-9]|\.)+")

          echo This version: $this_version
          echo Remote version: $remote_version
          dpkg --compare-versions $this_version gt $remote_version
      - name: Lint/Test
        run: TOX_PARALLEL_NO_SPINNER=1 poetry run tox -p
  
  build_and_publish:
    if: github.ref == 'refs/heads/master'
    needs: quality_assurance
    runs-on: ubuntu-latest
    container:
      image:  python:3.8-buster
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: poetry install
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
